ARG BASE_IMAGE=senzing/senzing-base:1.6.3
FROM ${BASE_IMAGE}

ENV REFRESHED_AT=2021-12-07

LABEL Name="senzing/web-app-demo-unstable" \
      Maintainer="support@senzing.com" \
      Version="2.0.0"

HEALTHCHECK CMD ["/app/healthcheck.sh"]

# Run as "root" for system installation.

USER root

# Install packages via apt.
# Note: There is a work-around for a lsb_release problem in the following RUN command.

RUN apt-get update \
 && apt-get -y install \
      apt-transport-https \
      apt-utils \
      curl \
      default-jdk \
      fio \
      htop \
      iotop \
      ipython \
      itop \
      less \
      odbc-postgresql \
      net-tools \
      pstack \
      python-pyodbc \
      supervisor \
      unixodbc \
      unixodbc-dev \
      vim \
 && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
 && apt-get -y install \
      build-essential \
      nodejs \
 && rm -rf /var/lib/apt/lists/*

# Install packages via pip.

RUN pip3 install \
    csvkit \
    fuzzywuzzy \
    ptable \
    pandas \
    python-levenshtein \
    pyodbc \
    setuptools

# Copy files from other docker images.

COPY --from=senzing/senzing-api-server:latest    "/app/senzing-api-server.jar" "/app/senzing-api-server.jar"
COPY --from=senzing/entity-search-web-app:latest "/app/" "/app/"

# Copy files from repository.

COPY ./rootfs /

# Install NPM program.

WORKDIR /app
RUN npm init -y \
 && npm install

# Service exposed on port 80.

EXPOSE 80

# Temporary work around until the following is resolved:
# https://github.com/Senzing/entity-search-web-app/issues/107

RUN touch /app/proxy.conf.json \
 && chmod 777 /app/proxy.conf.json

# Make non-root container.

# USER 1001

# Runtime execution.

ENV SENZING_API_SERVER_URL="http://localhost:8090"
ENV SENZING_WEB_SERVER_ADMIN_AUTH_MODE: 'JWT'
ENV SENZING_WEB_SERVER_ADMIN_AUTH_PATH: 'http://localhost:80'
ENV SENZING_WEB_SERVER_API_PATH="/api"
ENV SENZING_WEB_SERVER_PORT=80
ENV SENZING_WEB_SERVER_URL: "http://localhost:80"

WORKDIR /app
CMD ["/usr/bin/supervisord", "--nodaemon"]
