name: docker push containers to dockerhub and ecr

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  docker-push-containers-to-dockerhub-and-ecr-amd:
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    secrets:
      AWS_DOCKER_ACCOUNT_ID: ${{ secrets.AWS_DOCKER_ACCOUNT_ID }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    uses: senzing-factory/build-resources/.github/workflows/docker-push-containers-to-dockerhub-and-ecr.yaml@v2
    with:
      build-options: "--push"
      docker-image-repository: senzing/web-app-demo
      ecr-image-repository: senzing/web-app-demo
      image-tag: ${{ github.ref_name }}
      platforms: "linux/amd64"

  docker-push-containers-to-dockerhub-and-ecr-arm:
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    secrets:
      AWS_DOCKER_ACCOUNT_ID: ${{ secrets.AWS_DOCKER_ACCOUNT_ID }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    uses: senzing-factory/build-resources/.github/workflows/docker-push-containers-to-dockerhub-and-ecr.yaml@v2
    with:
      build-options: "--push"
      docker-image-repository: senzing/web-app-demo
      ecr-image-repository: senzing/web-app-demo
      image-tag: ${{ github.ref_name }}
      platforms: "linux/amd64"
